title: Taiwanese Foods
timezone: America/Los_Angeles
url: https://justinjay.wang/taiwanese-foods/
baseurl: /taiwanese-foods
description: A pinyin alphabetical list by Justin Jay Wang (王淳駿)
collections:
  posts:
    title: Posts
    output: false
  uploads:
    title: Uploads
    output: true
  foods:
    title: Foods
    output: false
defaults:
- scope:
    path: ''
  values:
    layout: page
- scope:
    path: ''
    type: posts
  values:
    layout: page
- scope:
    path: ''
    type: foods
  values:
    permalink: '/:title/'
permalink: pretty
exclude:
- Gemfile
- Gemfile.lock
- README*
- '.gitignore'
- package.json
- package-lock.json
- node_modules
- Gruntfile.js
plugins:
- jekyll-sitemap
- jekyll-redirect-from
- jekyll-seo-tag
twitter:
  username: justinjaywang
social_image: /assets/images/beef-noodle-soup.jpg
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: true
highlighter: rouge
excerpt_separator: |2+



sass:
  sass_dir: assets/styles/
  style: compressed
repository: justinjaywang/foods-from-taiwan
google_analytics: UA-15132368-17
